"""A log is a record of events, messages, or errors generated by software applications, typically used to track the application's behavior, debug issues, and monitor its performance."""

from loguru import logger
import sys
logger.remove()


logger.add(sys.stdout, format="{time:DD-MM-YYYY hh:mm:ss A} {level} {message}", level="INFO")


logger.add("logs/app.log", format="{time:DD-MM-YYYY hh:mm:ss A} {level} {message}", level="INFO", rotation="10 MB", compression="zip")


"""
min to max log level 
if you set log level to debug then it will show all the log like debug info warning error and critical 

if you set the log level to info then it will show only info warning error and critical it will not show the debug log 

DEBUG
INFO
WARNING
ERROR
CRITICAL
"""